// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/infinity-oj/cli/internal/app"
	"github.com/infinity-oj/cli/internal/clients"
	"github.com/infinity-oj/cli/internal/clients/accounts"
	accounts2 "github.com/infinity-oj/cli/internal/commands/accounts"
	"github.com/infinity-oj/cli/internal/config"
	"github.com/infinity-oj/cli/internal/service"
	"github.com/urfave/cli/v2"
)

// Injectors from wire.go:

func CreateApp(cf string) (*cli.App, error) {
	viper, err := config.New(cf)
	if err != nil {
		return nil, err
	}
	options, err := clients.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	client := clients.NewClient(options)
	accountsClient := accounts.NewAccountClient(client)
	accountService := service.NewAccountService(accountsClient)
	command := accounts2.NewAccountsCommands(accountService)
	cliApp := app.NewApp(command)
	return cliApp, nil
}

// wire.go:

var providerSet = wire.NewSet(config.ProviderSet, accounts2.ProviderSet, service.ProviderSet, app.ProviderSet, clients.ProviderSet)
